### Under Review

1. **Benxia Hu**^#^, Yuqiang Shi^#^, Feng Xiong, Xiaoyu Zhu, Yi-Ting Chen, Xingzhao Wen, Nathan Drolet, Leng Han, Xiang-min Xu, Dung-Fang Lee, Claudio Soto, Sheng Zhong, Hui Zheng, Wenbo Li^\*^. Rewired m6A methylation of upstream antisense RNAs in Alzheimer’s disease alters global gene transcription in the 3D nucleome (under review).  

2. Kai Zhang^#^, Kaiyuan Liu^#^, **Benxia Hu**^#^,Genyu Du, Xinyu Chen, Lingling Xiao, Yingchao Zhang, Luyao Jiang, Jing Na, Chaping Cheng, Jinming Wang, Penghui Xu, You Wang, Pengfei Ma, Guanglei Zhuang, Huifang Zhao, Yujiao Sun, Deng Wang, Qi Wang, Wei Xue, Wei-qiang Gao, Pengcheng Zhang^\*^, He Helen Zhu^\*^. Iron-Loaded Cancer-Associated Fibroblasts Induce Immunosuppression in Prostate Cancer (under review).  

3. Zilong Zhao^#^, **Benxia Hu**^#^, Yalan Deng^#^, Melinda Soeung, Jun Yao, Tina K. Nguyen, Yaohua Zhang, Zhou Jiang, Jian Gao, Shuang Peng, Bora Lim, Linghua Wang, Qing Zhang, Li Ma, Leng Han, Dihua Yu, Michael Curran, Giannicola Genovese, Boyi Gan, Wenbo Li^\*^, Palvos Msaoue^\*^, Liuqing Yang^\*^, Chunru Lin^\*^. Rewired 3D Genome Architecture in Sickle Cell Disease Mitigates T cell Ferroptosis in Renal Medullary Carcinoma (under review).  

4. **Benxia Hu**^#^, Huimeng Lu^#^, ALun Li^#^, Gang Li, JingJing Li, Depeng Wang, José R. Sandoval, Adeola Oluwakemi Ayoola, Jue Ruan^\*^, Dongdong Wu^\*^, Sheng Wang^\*^. Comparative analyses of diverse human long-read assemblies inform genomic divergence between African and non-African (under review).  

### Publications
5. Jiang Hu, Zhuo Wang, Zongyi Sun, **Benxia Hu**, Adeola Oluwakemi Ayoola, Fan Liang, Jingjing Li, José Raul Sandoval, David N Cooper, Kai Ye, Jue Ruan, Chuan-Le Xiao, DePeng Wang, Dong-Dong Wu^\*^, Sheng Wang^\*^. NextDenovo: an efficient error correction and accurate assembly tool for noisy long reads. (https://link.springer.com/article/10.1186/s13059-024-03252-4). Genome Biology. 2024,25:107.  

6. **Benxia Hu**^#^, Xiao-Lin Zhuang^#^, Long Zhou^#^, Guojie Zhang, Dong-Dong Wu^\*^. Deciphering rapidly evolving conserved elements in the primate adult brain development and Alzheimer’s disease. (https://academic.oup.com/mbe/article/41/1/msae001/7510690).Molecular Biology and Evolution. 2024,01.1093.  

7. Zhuang X^#^, Zhang J^#^, Shao Y^#^, Ye Y^#^, Chen CY, Zhou L, Wang Z, Luo X, Su B, Yao Y, Cooper D, **Hu B**, Wang L, Qi X, Lin J, Zhang G†, Wang W^\*^, Sheng N^\*^, Wu D^\*^. Integrative omics reveals rapidly evolving regulatory sequences driving primate brain evolution. (https://academic.oup.com/mbe/article/40/8/msad173/7231444). Molecular Biology and Evolution. 2023,10.1093.  

8. Sey NYA, **Benxia Hu**, Iskhakova M, Sun H, Shokrian N, Hutta G, Marks J, Quach BC, Johnson EO, Hancock DB, Akbarian S^\*^, Won H^\*^. Chromatin architecture in addiction circuitry identifies risk genes and potential biological mechanisms underlying cigarette smoking and alcohol use traits (https://www.nature.com/articles/s41380-022-01558-y). Molecular Psychiatry. 2022,27:3085–3094.  

9. Plaza-Jennings AL, Valada A, O'Shea C, Iskhakova M,**Hu B**, Javidfar B, Ben Hutta G, Lambert TY, Murray J, Kassim B, Chandrasekaran S, Chen BK, Morgello S†,Won H^\*^, Akbarian S^\*^. HIV integration in the human brain is linked to microglial activation and 3D genome remodeling. Molecular Cell. 2022,11.016.  

10. **Hu B**^#^, Won H^#^^\*^, Mah W, Park R, Kassim B, Spiess K, Kozlenkov A, Crowley CA, Pochareddy S, PsychENCODE consortium, Li Y, Dracheva S, Sestan N, Akbarian S, Geschwind DH^\*^. Neuronal and glial 3D chromatin architecture informs the cellular etiology of brain disorders. Nature Communications. 2021, 12:3968.  

11. Crowley C, Yang Y^\*^, Qiu Y, **Hu B**, Abnousi A, Lipinski J, Plewczynski D, Wu D, Won H, Ren B, Hu M^\*^, Li Y^\*^. FIREcaller: Detecting frequently interacting regions from Hi-C data (https://www.sciencedirect.com/science/article/pii/S2001037020305511). Computational and Structural Biotechnology Journal. 2021,19:355-362.  

12. **Hu B**, Won H^\*^. Chromatin architecture provides a roadmap to improve our understanding of psychiatric disorders (https://www.nature.com/articles/s41386-020-00822-5). Neuropsychopharmacology. 2020,46:234–235.  

13. Sey NYA, **Hu B**, Mah W, Fauni H, McAfee JC, Rajarajan P, Brennand KJ, Akbarian S, Won H^\*^. A computational tool (H-MAGMA) for improved prediction of brain-disorder risk genes by incorporating brain chromatin interaction profiles (https://www.nature.com/articles/s41593-020-0603-0). Nature Neuroscience. 2020,23:583-593.  

14. Lang F^\#^, Li X^\#^, Vladimirova O, **Hu B**, Chen G, Xiao Y, Singh V, Lu D, Li L, Han H, Wickramasinghe JM, Smith ST, Zheng C, Li Q, Lieberman PM, Fraser NW, Zhou J^\*^". CTCF interacts with the lytic HSV-1 genome to promote viral transcription (https://www.nature.com/articles/srep39861). Scientific Reports. 2017,7:39861.  

15. **Hu B**, Huo Y, Yang L, Chen G, Luo M, Yang J, Zhou J^\*^. ZIKV infection effects changes in gene splicing, isoform composition and lncRNA expression in human neural progenitor cells (https://virologyj.biomedcentral.com/articles/10.1186/s12985-017-0882-6). Virology Journal. 2017,14:217.  

16. **Hu B**, Huo Y, Chen G, Yang L, Wu D, Zhou J^\*^. Functional prediction of differentially expressed lncRNAs in HSV-1 infected human foreskin fibroblasts (https://virologyj.biomedcentral.com/articles/10.1186/s12985-016-0592-5). Virology Journal. 2016,13:137.  

17. **Hu B**^\#^, Li X^\#^, Huo Y, Yu Y, Zhang Q, Chen G, Zhang Y, Fraser NW, Wu D^\*^, Zhou J^\*^. Cellular responses to HSV-1 infection are linked to specific types of alterations in the host transcriptome (https://www.nature.com/articles/srep28075). Scientific Reports. 2016,6:28075.  
